- name: Ruby | Checking installed version
  shell: ruby -v | grep -o "ruby {{ ruby_version }}"
  register: _installed
  ignore_errors: True

- name: Ruby | Download
  get_url: "url={{ ruby_url }} dest={{ ruby_tmp_path }}.tar"
  when: _installed.rc == 1

- name: Ruby | Extract
  # command: tar -zxf "{{ ruby_tmp_path }}.tar"
  unarchive:
    src: "{{ ruby_tmp_path }}.tar"
    dest: "{{ ruby_tmp_dir }}"
    remote_src: True
  when: _installed.rc == 1
- name: Install build-essential
  command: apt-get install -y build-essential
  become: yes
  when: _installed.rc == 1
- name: Install libssl-dev
  command: apt-get install -y libssl-dev
  become: yes
  when: _installed.rc == 1
- name: Make, configure, and install ruby
  command: "{{ item }} chdir={{ ruby_tmp_path }}"
  with_items:
    - ./configure
    - make
    - sudo make install
  when: _installed.rc == 1
